name: Send Daily Stock Email

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 00:00 = 한국 시간 오전 9시
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ 저장소 클론
        uses: actions/checkout@v3

      - name: ✅ 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ✅ 의존성 설치
        run: pip install -r requirements.txt

      - name: Run the app
        run: python app.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_ADDRESS:   ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD:  ${{ secrets.EMAIL_PASSWORD }}
